# Generated by Django 4.2.13 on 2024-06-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invest", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deposit",
            name="plan",
            field=models.CharField(
                choices=[
                    ("test", "TEST PLAN"),
                    ("standard", "STARTER PLAN"),
                    ("premium", "PREMIUM PLAN"),
                ],
                max_length=20,
            ),
        ),
    ]
